### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore.UI#11]
When I try to debug a query 

fromAll().
    when({
        $init : function(s,e) {return {count : 0}},
        $any : function(s,e) {throw "foo";  s.count+=1}
    })

I get dropped in the same place as in old ui but when I try to step in on the handler() I end up in the following code instead of the query code

```
    function defaultEventHandler(state, eventEnvelope) {
        return eventEnvelope.isJson ? eventEnvelope.body : { $e: eventEnvelope.bodyRaw };
    }
```

**Comment by TAGC** [comment]
Same issue here. Trying to set up my first projection stream:

```javascript
options({
    resultStreamName: 'SO_FreeManufacturerServicePlans',
    $includeLinks: true,
    reorderEvents: false,
    processingLag: 0
});

fromStream('$et-SO_ServicePlanAdded')
.when({    
    SO_ServicePlanAdded: function(state, event) {
        var isManufacturerServicePlan = e.data.ProductCode.includes("ConfigID: ManufacturerSP");
        var isFree = e.data.Price <= 0;
        if (isManufacturerServicePlan && isFree) {
            log('Free manufacturer service plan: ' + JSON.stringify(e));
        }
        else
        {
            log('Normal service plan: ' + JSON.stringify(e));
        }
    }
})
```

When I hit "Run Step" while debugging it, it has the `handler` variable set to `defaultEventHandler`: 
![image](https://user-images.githubusercontent.com/1588951/156201525-86460eec-cae0-4f75-adf4-aa0c808d5667.png)

In the browser console output, I see this message:

> Failed to load resource: the server responded with a status of 401 (Unauthorized)

Which references this request: https://my-company-event-store-server/projection/SO_FreeManufacturerServicePlans/query

If I navigate to that link in the browser, I get an HTTP 401 error.
