### ISSUE TITLE
cannot create projection, button disabled

### ISSUE THREAD

**Issue by robvdlv** [EventStore/EventStore.UI#115]
Hi,

I am trying to create a projection via the Web UI.
I am using 3.4.0 release of the EventStore, started with 

> C:\es-win-3.4.0>EventStore.ClusterNode.exe --run-projections All -start-standard-projections

But fail to create any projection (e.g.)

```
fromCategory('order')
    .whenAny(function(s,e) {
        linkTo('orders',e);
    });
```
because the create button is disabled in terms of styling and function.
I have tried this in:

- Firefox 43.04
- Chrome 48.0.2564.109 m
- IE 11.0.9600.18161

Note that I don't see any errors in the javascript console.
Am I overlooking something causing this not to work or is this possibly a bug?

Regards,

Rob

**Comment by pgermishuys** [comment]
The button is disabled unless you provide

- Name for the projection
- Projection body

![image](https://cloud.githubusercontent.com/assets/1062417/13018315/87cb5cb6-d1d1-11e5-91d7-17ff784985b7.png)

This is with the required fields filled in on 3.4.0.0
![image](https://cloud.githubusercontent.com/assets/1062417/13018395/e7553454-d1d1-11e5-8c98-4f36bf39a9b7.png)

**Comment by robvdlv** [comment]
I can't believe I missed that. Must have been sitting behind the screen for too long.

Thanks for pointing out, will close issue.

Rob
