### ISSUE TITLE
Replica Status not updating correctly.

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore.UI#124]
If the master changes during catching up, the ReplicaStatus stops updating.

Scenario:
1 Master - Alive
2 Slave - Alive
3 Catchingup - Alive

If you shutdown `master`. The Replica Status on the web page stops updating itself.
Upon 1 coming back to life, the ReplicaStatus updated to the following.

![screen shot 2016-05-18 at 8 53 11 am](https://cloud.githubusercontent.com/assets/1062417/15349829/fe61302c-1cd5-11e6-9f2d-5c7d1cb14342.png)

**Comment by gregoryyoung** [comment]
Is this with the UI connected to the master?

**Comment by hayley-jean** [comment]
This should have been fixed in 21.10
