### ISSUE TITLE
Error message dashboard

### ISSUE THREAD

**Issue by suddenelfilio** [EventStore/EventStore.UI#125]
we are receiving the following issue.

![image](https://cloud.githubusercontent.com/assets/6460448/15566970/15274608-2324-11e6-8c1a-3252b61a921e.png)

also developer tools show:

![image](https://cloud.githubusercontent.com/assets/6460448/15567000/3765f99e-2324-11e6-94a1-c02484c610ba.png)

**Comment by pgermishuys** [comment]
Mind giving us a little more information such as whether for instance issuing a request to `http://172.30.78.4:1112/stats` actually works?

**Comment by suddenelfilio** [comment]
surfing to that page turns up http 200 and blank, when it is being called throughjs it is 404, very strange...

**Comment by suddenelfilio** [comment]
Sorry previous oberservation was incorrect: surfing also gives a 404
![image](https://cloud.githubusercontent.com/assets/6460448/15567668/d880cf2c-2327-11e6-976d-c22aee3db630.png)

**Comment by gregoryyoung** [comment]
Can you describe your http setup? eg what are internal vs external ports? do you have a load balancer etc in front?

**Comment by pgermishuys** [comment]
Let's start by taking a look at your configuration since the ports you are using does matter and it will help in diagnosing your particular problem.

By default Event Store uses the following ports

- 1112 : Internal TCP Port
- 1113 : External TCP Port
- 2112 : Internal HTTP Port
- 2113 : External HTTP Port

**Comment by suddenelfilio** [comment]
1112 is internal port an 1114 is external port, no LB 

I do see a more severe error on 1114
http://172.30.78.4:1112/stats
![image](https://cloud.githubusercontent.com/assets/6460448/15567858/f4e035f8-2328-11e6-9d8b-8564008bd159.png)

**Comment by pgermishuys** [comment]
Can you please provide us with the following information, when Event Store starts up it spits out it's effective configuration like so

```
[01347,01,08:00:09.982]
ES VERSION:               0.0.0.0 (release-v3.7.0/dbb4bb824bc1bbb260304655d11fae3f224ab175, Tue, 24 May 2016 14:14:45 +0200)
OS:                       MacOS (Unix 15.5.0.0)
RUNTIME:                  3.12.1 (tarball Sun Dec 27 16:42:40 SAST 2015) (64-bit)
GC:                       2 GENERATIONS
LOGS:                     /Users/pieterg/source/EventStore/bin/clusternode/logs

MODIFIED OPTIONS:

	MEM DB:                   True (Command Line)

DEFAULT OPTIONS:

	HELP:                     False (<DEFAULT>)
	VERSION:                  False (<DEFAULT>)
	LOG:                      /Users/pieterg/source/EventStore/bin/clusternode/logs (<DEFAULT>)
	CONFIG:                   <empty> (<DEFAULT>)
	DEFINES:                  <empty> (<DEFAULT>)
	WHAT IF:                  False (<DEFAULT>)
	START STANDARD PROJECTIONS: False (<DEFAULT>)
	DISABLE HTTP CACHING:     False (<DEFAULT>)
	MONO MIN THREADPOOL SIZE: 10 (<DEFAULT>)
	INT IP:                   127.0.0.1 (<DEFAULT>)
	EXT IP:                   127.0.0.1 (<DEFAULT>)
	INT HTTP PORT:            2112 (<DEFAULT>)
	EXT HTTP PORT:            2113 (<DEFAULT>)
	INT TCP PORT:             1112 (<DEFAULT>)
	INT SECURE TCP PORT:      0 (<DEFAULT>)
	EXT TCP PORT:             1113 (<DEFAULT>)
	EXT SECURE TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
	EXT SECURE TCP PORT:      0 (<DEFAULT>)
	EXT IP ADVERTISE AS:      <empty> (<DEFAULT>)
	EXT TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
	EXT HTTP PORT ADVERTISE AS: 0 (<DEFAULT>)
	INT IP ADVERTISE AS:      <empty> (<DEFAULT>)
	INT SECURE TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
```

Please provide us with the complete output.

**Comment by suddenelfilio** [comment]
`[PID:15140:001 2016.05.26 08:14:00.736 INFO  ProgramBase`1       ] 
ES VERSION:               3.6.2.0 (oss-v3.6.1-2-gb26c368/b26c3684e672a1d94ce484b0d74dd5bab8bcae52, Wed, 11 May 2016 09:44:03 +0200)
OS:                       Windows (Microsoft Windows NT 6.2.9200.0)
RUNTIME:                  .NET 4.0.30319.34209 (64-bit)
GC:                       3 GENERATIONS
LOGS:                     d:\es\logs\node1-log

MODIFIED OPTIONS:

	DB:                       d:\es\data\node1-db (Command Line)
	LOG:                      d:\es\logs\node1-log (Command Line)
	INT IP:                   172.30.76.17 (Command Line)
	EXT IP:                   172.30.76.17 (Command Line)
	INT TCP PORT:             1111 (Command Line)
	EXT TCP PORT:             1113 (Command Line)
	INT HTTP PORT:            1112 (Command Line)
	EXT HTTP PORT:            1114 (Command Line)
	STATS PERIOD SEC:         120 (Command Line)
	RUN PROJECTIONS:          All (Command Line)
	CLUSTER SIZE:             3 (Command Line)
	DISCOVER VIA DNS:         false (Command Line)
	GOSSIP SEED:              172.30.78.4:1112,172.30.78.12:1112 (Command Line)

DEFAULT OPTIONS:

	HELP:                     False (<DEFAULT>)
	VERSION:                  False (<DEFAULT>)
	CONFIG:                   <empty> (<DEFAULT>)
	DEFINES:                  <empty> (<DEFAULT>)
	WHAT IF:                  False (<DEFAULT>)
	START STANDARD PROJECTIONS: False (<DEFAULT>)
	DISABLE HTTP CACHING:     False (<DEFAULT>)
	MONO MIN THREADPOOL SIZE: 10 (<DEFAULT>)
	INT SECURE TCP PORT:      0 (<DEFAULT>)
	EXT SECURE TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
	EXT SECURE TCP PORT:      0 (<DEFAULT>)
	EXT IP ADVERTISE AS:      <empty> (<DEFAULT>)
	EXT TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
	EXT HTTP PORT ADVERTISE AS: 0 (<DEFAULT>)
	INT IP ADVERTISE AS:      <empty> (<DEFAULT>)
	INT SECURE TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
	INT TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
	INT HTTP PORT ADVERTISE AS: 0 (<DEFAULT>)
	INT TCP HEARTBEAT TIMEOUT: 700 (<DEFAULT>)
	EXT TCP HEARTBEAT TIMEOUT: 1000 (<DEFAULT>)
	INT TCP HEARTBEAT INTERVAL: 700 (<DEFAULT>)
	EXT TCP HEARTBEAT INTERVAL: 2000 (<DEFAULT>)
	FORCE:                    False (<DEFAULT>)
	NODE PRIORITY:            0 (<DEFAULT>)
	MIN FLUSH DELAY MS:       2 (<DEFAULT>)
	COMMIT COUNT:             -1 (<DEFAULT>)
	PREPARE COUNT:            -1 (<DEFAULT>)
	ADMIN ON EXT:             True (<DEFAULT>)
	STATS ON EXT:             True (<DEFAULT>)
	GOSSIP ON EXT:            True (<DEFAULT>)
	DISABLE SCAVENGE MERGING: False (<DEFAULT>)
	SCAVENGE HISTORY MAX AGE: 30 (<DEFAULT>)
	CLUSTER DNS:              fake.dns (<DEFAULT>)
	CLUSTER GOSSIP PORT:      30777 (<DEFAULT>)
	CACHED CHUNKS:            -1 (<DEFAULT>)
	CHUNKS CACHE SIZE:        536871424 (<DEFAULT>)
	MAX MEM TABLE SIZE:       1000000 (<DEFAULT>)
	INDEX:                    <empty> (<DEFAULT>)
	MEM DB:                   False (<DEFAULT>)
	SKIP DB VERIFY:           False (<DEFAULT>)
	PROJECTION THREADS:       3 (<DEFAULT>)
	WORKER THREADS:           5 (<DEFAULT>)
	INT HTTP PREFIXES:        <empty> (<DEFAULT>)
	EXT HTTP PREFIXES:        <empty> (<DEFAULT>)
	ENABLE TRUSTED AUTH:      False (<DEFAULT>)
	ADD INTERFACE PREFIXES:   True (<DEFAULT>)
	CERTIFICATE STORE LOCATION: <empty> (<DEFAULT>)
	CERTIFICATE STORE NAME:   <empty> (<DEFAULT>)
	CERTIFICATE SUBJECT NAME: <empty> (<DEFAULT>)
	CERTIFICATE THUMBPRINT:   <empty> (<DEFAULT>)
	CERTIFICATE FILE:         <empty> (<DEFAULT>)
	CERTIFICATE PASSWORD:     <empty> (<DEFAULT>)
	USE INTERNAL SSL:         False (<DEFAULT>)
	SSL TARGET HOST:          n/a (<DEFAULT>)
	SSL VALIDATE SERVER:      True (<DEFAULT>)
	AUTHENTICATION TYPE:      internal (<DEFAULT>)
	AUTHENTICATION CONFIG:    <empty> (<DEFAULT>)
	PREPARE TIMEOUT MS:       2000 (<DEFAULT>)
	COMMIT TIMEOUT MS:        2000 (<DEFAULT>)
	UNSAFE DISABLE FLUSH TO DISK: False (<DEFAULT>)
	BETTER ORDERING:          False (<DEFAULT>)
	UNSAFE IGNORE HARD DELETE: False (<DEFAULT>)
	INDEX CACHE DEPTH:        16 (<DEFAULT>)
	GOSSIP INTERVAL MS:       1000 (<DEFAULT>)
	GOSSIP ALLOWED DIFFERENCE MS: 60000 (<DEFAULT>)
	GOSSIP TIMEOUT MS:        500 (<DEFAULT>)
	ENABLE HISTOGRAMS:        False (<DEFAULT>)
	LOG HTTP REQUESTS:        False (<DEFAULT>)

[PID:15140:001 2016.05.26 08:14:00.908 INFO  ProgramBase`1       ] Quorum size set to 2
[PID:15140:001 2016.05.26 08:14:00.908 INFO  ProgramBase`1       ] Cannot find plugins path: d:\es\plugins
[PID:15140:001 2016.05.26 08:14:01.111 INFO  ProgramBase`1       ] INSTANCE ID:              e0b9d9a8-1a80-447a-936e-7eb804d4d0c2
[PID:15140:001 2016.05.26 08:14:01.111 INFO  ProgramBase`1       ] DATABASE:                 d:\es\data\node1-db
[PID:15140:001 2016.05.26 08:14:01.111 INFO  ProgramBase`1       ] WRITER CHECKPOINT:        68774 (0x10CA6)
[PID:15140:001 2016.05.26 08:14:01.111 INFO  ProgramBase`1       ] CHASER CHECKPOINT:        68774 (0x10CA6)
[PID:15140:001 2016.05.26 08:14:01.111 INFO  ProgramBase`1       ] EPOCH CHECKPOINT:         68253 (0x10A9D)
[PID:15140:001 2016.05.26 08:14:01.111 INFO  ProgramBase`1       ] TRUNCATE CHECKPOINT:      -1 (0xFFFFFFFFFFFFFFFF)
[PID:15140:001 2016.05.26 08:14:01.549 TRACE MessageHierarchy    ] MessageHierarchy initialization took 00:00:00.2446200.
[PID:15140:001 2016.05.26 08:14:01.799 TRACE TFChunk             ] CACHED TFChunk #0-0 (chunk-000000.000000) in 00:00:00.0089352.
[PID:15140:001 2016.05.26 08:14:02.705 INFO  MiniWeb             ] Starting MiniWeb for /web/es/js/projections ==> d:\es\projections
[PID:15140:001 2016.05.26 08:14:02.705 INFO  MiniWeb             ] Starting MiniWeb for /web/es/js/projections/v8/Prelude ==> d:\es\Prelude
[PID:15140:001 2016.05.26 08:14:02.721 TRACE MiniWeb             ] Binding MiniWeb to /web/es/js/projections/{*remaining_path}
[PID:15140:001 2016.05.26 08:14:02.721 TRACE MiniWeb             ] Binding MiniWeb to /web/es/js/projections/v8/Prelude/{*remaining_path}
[PID:15140:001 2016.05.26 08:14:02.721 TRACE MiniWeb             ] Binding MiniWeb to /web/es/js/projections/{*remaining_path}
[PID:15140:001 2016.05.26 08:14:02.721 TRACE MiniWeb             ] Binding MiniWeb to /web/es/js/projections/v8/Prelude/{*remaining_path}
[PID:15140:001 2016.05.26 08:14:02.768 INFO  MiniWeb             ] Starting MiniWeb for /web ==> d:\es\clusternode-web
[PID:15140:001 2016.05.26 08:14:02.768 TRACE MiniWeb             ] Binding MiniWeb to /web/{*remaining_path}
[PID:15140:001 2016.05.26 08:14:02.768 INFO  MiniWeb             ] Starting MiniWeb for /web ==> d:\es\clusternode-web
[PID:15140:001 2016.05.26 08:14:02.768 TRACE MiniWeb             ] Binding MiniWeb to /web/{*remaining_path}
[PID:15140:014 2016.05.26 08:14:02.799 INFO  ClusterVNodeControll] ========== [172.30.76.17:1112] SYSTEM INIT...
[PID:15140:014 2016.05.26 08:14:02.861 INFO  TcpServerListener   ] Starting Normal TCP listening on TCP endpoint: 172.30.76.17:1113.
[PID:15140:014 2016.05.26 08:14:02.861 INFO  TcpServerListener   ] Starting Normal TCP listening on TCP endpoint: 172.30.76.17:1111.
[PID:15140:015 2016.05.26 08:14:02.893 INFO  IndexCommitter      ] TableIndex initialization...
[PID:15140:014 2016.05.26 08:14:02.939 INFO  HttpAsyncServer     ] Starting HTTP server on [http://172.30.76.17:1114/]...
[PID:15140:015 2016.05.26 08:14:02.939 INFO  IndexCommitter      ] ReadIndex building...
[PID:15140:014 2016.05.26 08:14:02.939 INFO  HttpAsyncServer     ] HTTP server is up and listening on [http://172.30.76.17:1114/]
[PID:15140:014 2016.05.26 08:14:03.002 TRACE InMemoryBus         ] SLOW BUS MSG [MainBus]: SystemInit - 78ms. Handler: HttpService.
[PID:15140:014 2016.05.26 08:14:03.002 INFO  HttpAsyncServer     ] Starting HTTP server on [http://172.30.76.17:1112/]...
[PID:15140:014 2016.05.26 08:14:03.002 INFO  HttpAsyncServer     ] HTTP server is up and listening on [http://172.30.76.17:1112/]`

**Comment by suddenelfilio** [comment]
while I restarted the node the error went away... when looking at 1112, the 1114 still has a 503

[PID:06720:001 2016.05.26 08:22:41.448 INFO  ProgramBase`1       ] 
ES VERSION:               3.6.2.0 (oss-v3.6.1-2-gb26c368/b26c3684e672a1d94ce484b0d74dd5bab8bcae52, Wed, 11 May 2016 09:44:03 +0200)
OS:                       Windows (Microsoft Windows NT 6.2.9200.0)
RUNTIME:                  .NET 4.0.30319.34209 (64-bit)
GC:                       3 GENERATIONS
LOGS:                     d:\es\logs\node1-log

MODIFIED OPTIONS:

	DB:                       d:\es\data\node1-db (Command Line)
	LOG:                      d:\es\logs\node1-log (Command Line)
	INT IP:                   172.30.78.4 (Command Line)
	EXT IP:                   172.30.78.4 (Command Line)
	INT TCP PORT:             1111 (Command Line)
	EXT TCP PORT:             1113 (Command Line)
	INT HTTP PORT:            1112 (Command Line)
	EXT HTTP PORT:            1114 (Command Line)
	STATS PERIOD SEC:         120 (Command Line)
	RUN PROJECTIONS:          All (Command Line)
	CLUSTER SIZE:             3 (Command Line)
	DISCOVER VIA DNS:         false (Command Line)
	GOSSIP SEED:              172.30.78.12:1112,172.30.76.17:1112 (Command Line)

DEFAULT OPTIONS:

	HELP:                     False (<DEFAULT>)
	VERSION:                  False (<DEFAULT>)
	CONFIG:                   <empty> (<DEFAULT>)
	DEFINES:                  <empty> (<DEFAULT>)
	WHAT IF:                  False (<DEFAULT>)
	START STANDARD PROJECTIONS: False (<DEFAULT>)
	DISABLE HTTP CACHING:     False (<DEFAULT>)
	MONO MIN THREADPOOL SIZE: 10 (<DEFAULT>)
	INT SECURE TCP PORT:      0 (<DEFAULT>)
	EXT SECURE TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
	EXT SECURE TCP PORT:      0 (<DEFAULT>)
	EXT IP ADVERTISE AS:      <empty> (<DEFAULT>)
	EXT TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
	EXT HTTP PORT ADVERTISE AS: 0 (<DEFAULT>)
	INT IP ADVERTISE AS:      <empty> (<DEFAULT>)
	INT SECURE TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
	INT TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
	INT HTTP PORT ADVERTISE AS: 0 (<DEFAULT>)
	INT TCP HEARTBEAT TIMEOUT: 700 (<DEFAULT>)
	EXT TCP HEARTBEAT TIMEOUT: 1000 (<DEFAULT>)
	INT TCP HEARTBEAT INTERVAL: 700 (<DEFAULT>)
	EXT TCP HEARTBEAT INTERVAL: 2000 (<DEFAULT>)
	FORCE:                    False (<DEFAULT>)
	NODE PRIORITY:            0 (<DEFAULT>)
	MIN FLUSH DELAY MS:       2 (<DEFAULT>)
	COMMIT COUNT:             -1 (<DEFAULT>)
	PREPARE COUNT:            -1 (<DEFAULT>)
	ADMIN ON EXT:             True (<DEFAULT>)
	STATS ON EXT:             True (<DEFAULT>)
	GOSSIP ON EXT:            True (<DEFAULT>)
	DISABLE SCAVENGE MERGING: False (<DEFAULT>)
	SCAVENGE HISTORY MAX AGE: 30 (<DEFAULT>)
	CLUSTER DNS:              fake.dns (<DEFAULT>)
	CLUSTER GOSSIP PORT:      30777 (<DEFAULT>)
	CACHED CHUNKS:            -1 (<DEFAULT>)
	CHUNKS CACHE SIZE:        536871424 (<DEFAULT>)
	MAX MEM TABLE SIZE:       1000000 (<DEFAULT>)
	INDEX:                    <empty> (<DEFAULT>)
	MEM DB:                   False (<DEFAULT>)
	SKIP DB VERIFY:           False (<DEFAULT>)
	PROJECTION THREADS:       3 (<DEFAULT>)
	WORKER THREADS:           5 (<DEFAULT>)
	INT HTTP PREFIXES:        <empty> (<DEFAULT>)
	EXT HTTP PREFIXES:        <empty> (<DEFAULT>)
	ENABLE TRUSTED AUTH:      False (<DEFAULT>)
	ADD INTERFACE PREFIXES:   True (<DEFAULT>)
	CERTIFICATE STORE LOCATION: <empty> (<DEFAULT>)
	CERTIFICATE STORE NAME:   <empty> (<DEFAULT>)
	CERTIFICATE SUBJECT NAME: <empty> (<DEFAULT>)
	CERTIFICATE THUMBPRINT:   <empty> (<DEFAULT>)
	CERTIFICATE FILE:         <empty> (<DEFAULT>)
	CERTIFICATE PASSWORD:     <empty> (<DEFAULT>)
	USE INTERNAL SSL:         False (<DEFAULT>)
	SSL TARGET HOST:          n/a (<DEFAULT>)
	SSL VALIDATE SERVER:      True (<DEFAULT>)
	AUTHENTICATION TYPE:      internal (<DEFAULT>)
	AUTHENTICATION CONFIG:    <empty> (<DEFAULT>)
	PREPARE TIMEOUT MS:       2000 (<DEFAULT>)
	COMMIT TIMEOUT MS:        2000 (<DEFAULT>)
	UNSAFE DISABLE FLUSH TO DISK: False (<DEFAULT>)
	BETTER ORDERING:          False (<DEFAULT>)
	UNSAFE IGNORE HARD DELETE: False (<DEFAULT>)
	INDEX CACHE DEPTH:        16 (<DEFAULT>)
	GOSSIP INTERVAL MS:       1000 (<DEFAULT>)
	GOSSIP ALLOWED DIFFERENCE MS: 60000 (<DEFAULT>)
	GOSSIP TIMEOUT MS:        500 (<DEFAULT>)
	ENABLE HISTOGRAMS:        False (<DEFAULT>)
	LOG HTTP REQUESTS:        False (<DEFAULT>)

[PID:06720:001 2016.05.26 08:22:41.698 INFO  ProgramBase`1       ] Quorum size set to 2
[PID:06720:001 2016.05.26 08:22:41.698 INFO  ProgramBase`1       ] Cannot find plugins path: d:\es\plugins
[PID:06720:001 2016.05.26 08:22:41.932 INFO  ProgramBase`1       ] INSTANCE ID:              37313250-fce9-437b-8c25-868c2eb1d5cb
[PID:06720:001 2016.05.26 08:22:41.932 INFO  ProgramBase`1       ] DATABASE:                 d:\es\data\node1-db
[PID:06720:001 2016.05.26 08:22:41.932 INFO  ProgramBase`1       ] WRITER CHECKPOINT:        135595 (0x211AB)
[PID:06720:001 2016.05.26 08:22:41.932 INFO  ProgramBase`1       ] CHASER CHECKPOINT:        135595 (0x211AB)
[PID:06720:001 2016.05.26 08:22:41.932 INFO  ProgramBase`1       ] EPOCH CHECKPOINT:         83485 (0x1461D)
[PID:06720:001 2016.05.26 08:22:41.932 INFO  ProgramBase`1       ] TRUNCATE CHECKPOINT:      -1 (0xFFFFFFFFFFFFFFFF)
[PID:06720:001 2016.05.26 08:22:42.261 TRACE MessageHierarchy    ] MessageHierarchy initialization took 00:00:00.1317288.
[PID:06720:001 2016.05.26 08:22:42.558 TRACE TFChunk             ] CACHED TFChunk #0-0 (chunk-000000.000000) in 00:00:00.0103326.
[PID:06720:001 2016.05.26 08:22:43.901 INFO  MiniWeb             ] Starting MiniWeb for /web/es/js/projections ==> d:\es\projections
[PID:06720:001 2016.05.26 08:22:43.901 INFO  MiniWeb             ] Starting MiniWeb for /web/es/js/projections/v8/Prelude ==> d:\es\Prelude
[PID:06720:001 2016.05.26 08:22:43.917 TRACE MiniWeb             ] Binding MiniWeb to /web/es/js/projections/{*remaining_path}
[PID:06720:001 2016.05.26 08:22:43.917 TRACE MiniWeb             ] Binding MiniWeb to /web/es/js/projections/v8/Prelude/{*remaining_path}
[PID:06720:001 2016.05.26 08:22:43.917 TRACE MiniWeb             ] Binding MiniWeb to /web/es/js/projections/{*remaining_path}
[PID:06720:001 2016.05.26 08:22:43.917 TRACE MiniWeb             ] Binding MiniWeb to /web/es/js/projections/v8/Prelude/{*remaining_path}
[PID:06720:001 2016.05.26 08:22:43.948 INFO  MiniWeb             ] Starting MiniWeb for /web ==> d:\es\clusternode-web
[PID:06720:001 2016.05.26 08:22:43.948 TRACE MiniWeb             ] Binding MiniWeb to /web/{*remaining_path}
[PID:06720:001 2016.05.26 08:22:43.948 INFO  MiniWeb             ] Starting MiniWeb for /web ==> d:\es\clusternode-web
[PID:06720:001 2016.05.26 08:22:43.948 TRACE MiniWeb             ] Binding MiniWeb to /web/{*remaining_path}
[PID:06720:014 2016.05.26 08:22:43.995 INFO  ClusterVNodeControll] ========== [172.30.78.4:1112] SYSTEM INIT...
[PID:06720:014 2016.05.26 08:22:44.057 INFO  TcpServerListener   ] Starting Normal TCP listening on TCP endpoint: 172.30.78.4:1113.
[PID:06720:014 2016.05.26 08:22:44.057 INFO  TcpServerListener   ] Starting Normal TCP listening on TCP endpoint: 172.30.78.4:1111.
[PID:06720:015 2016.05.26 08:22:44.089 INFO  IndexCommitter      ] TableIndex initialization...
[PID:06720:015 2016.05.26 08:22:44.120 INFO  IndexCommitter      ] ReadIndex building...
[PID:06720:014 2016.05.26 08:22:44.151 INFO  HttpAsyncServer     ] Starting HTTP server on [http://172.30.78.4:1114/]...
[PID:06720:014 2016.05.26 08:22:44.151 INFO  HttpAsyncServer     ] HTTP server is up and listening on [http://172.30.78.4:1114/]
[PID:06720:014 2016.05.26 08:22:44.229 TRACE InMemoryBus         ] SLOW BUS MSG [MainBus]: SystemInit - 93ms. Handler: HttpService.
[PID:06720:014 2016.05.26 08:22:44.229 INFO  HttpAsyncServer     ] Starting HTTP server on [http://172.30.78.4:1112/]...
[PID:06720:014 2016.05.26 08:22:44.229 INFO  HttpAsyncServer     ] HTTP server is up and listening on [http://172.30.78.4:1112/]
[PID:06720:014 2016.05.26 08:22:44.293 TRACE QueuedHandlerMRES   ] SLOW QUEUE MSG [MainQueue]: SystemInit - 296ms. Q: 0/6.
[PID:06720:014 2016.05.26 08:22:44.293 INFO  ClusterVNodeControll] ========== [172.30.78.4:1112] Service 'StorageReader' initialized.
[PID:06720:014 2016.05.26 08:22:44.293 INFO  ClusterVNodeControll] ========== [172.30.78.4:1112] Service 'StorageWriter' initialized.
[PID:06720:015 2016.05.26 08:22:44.323 DEBUG IndexCommitter      ] ReadIndex rebuilding done: total processed 128 records, time elapsed: 00:00:00.2032042.

**Comment by pgermishuys** [comment]
Since you are seeing this on `windows` and the `503`, I suspect you are encountering an `acl` issue.
Read the section on **If you get 503 errors from the web UI** over here http://docs.geteventstore.com/server/3.6.0/

**Comment by pgermishuys** [comment]
@suddenelfilio do you have any feedback for us regarding this issue?

**Comment by suddenelfilio** [comment]
No currently at the Pizza Hut ☺

**Comment by alexeyzimarev** [comment]
@suddenelfilio probably you're done with Pizza Hut now, may be you can write something :)

**Comment by suddenelfilio** [comment]
Yes, that is correct. I regret to report that we abandoned Eventstore for our project. You can close this ticket .
