### ISSUE TITLE
Slash in stream name returns 404

### ISSUE THREAD

**Issue by SabrinaMH** [EventStore/EventStore.UI#131]
I have a stream with id `Task-project/test/task/a new test`
When I try to view it in the UI using the url 
`http://127.0.0.1:2113/streams/Task-project%2Ftest%2Ftask%2Fa%20new%20test`
then I get 404.
However, from EventStores perspective there's nothing wrong with the stream id as I can easily use its .NET API to retrieve the stream.

**Comment by pgermishuys** [comment]
Same issue has been reported here (https://github.com/EventStore/EventStore/issues/804). We need to find a good way of handling this.
For interest sake, for what reason have you used slashes and spaces in your stream name?

**Comment by SabrinaMH** [comment]
Ah, hadn't seen that one. Thanks!
The slashes and spaces appear due to natural aggregate ids, e.g. a Project aggregate with project title "Test" ends up with id Project/Test. And the stream name is chosen as a concatenation of the aggregate type and its id (separated by a hyphen).

**Comment by wldevries** [comment]
A backslash in the stream name is even worse. When you click on it in the stream browser you get the error that the stream does not exist

**Comment by hayley-jean** [comment]
This has been fixed: https://github.com/EventStore/EventStore/issues/804#issuecomment-999420090
