### ISSUE TITLE
Competing Consumer timeouts

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore.UI#141]
Right now if you enter values such as 0 it replaces it with defaults. This likely breaks the least surprise principle.

**Comment by mjgpy3** [comment]
@gregoryyoung it looks like EventStore's proper is creating the defaults.

For example, if I fill out a new Subscription with all 0s it PUTs
```json
{
    "bufferSize": "0",
    "checkPointAfterMilliseconds": "0",
    "checkpoints": 1000,
    "extraStatistics": false,
    "liveBufferSize": "0",
    "maxCheckPointCount": "0",
    "maxRetryCount": "0",
    "maxSubscriberCount": "0",
    "messageTimeoutMilliseconds": "0",
    "minCheckPointCount": "0",
    "namedConsumerStrategy": "RoundRobin",
    "readBatchSize": "0",
    "resolveLinktos": false,
    "startFrom": 0
}
```
to http://localhost:2113/subscriptions/some-stream/some-group-3

and returns a 201 Created.

The later `GET /info` request returns a config of

```json
```

**Comment by hayley-jean** [comment]
This has been fixed in https://github.com/EventStore/EventStore/issues/1479
