### ISSUE TITLE
Projections UI shows projection source code on one single line when uploaded via HTTP API

### ISSUE THREAD

**Issue by akaegi** [EventStore/EventStore.UI#145]
When creating a projection via HTTP API 
`curl -d@projection.js http://127.0.0.1:2113/projections/continuous?name=testProj -u admin:changeit`
the EventStore Web Interface shows the source code of the projection (Projections > Edit) on a single line.
This makes updating the projection very cumbersome.

ES Version: 3.9.3.0

**Comment by pgermishuys** [comment]
@akaegi to preserve the new lines, you likely want to use `--data-binary` instead of `-d` when posting.

**Comment by pgermishuys** [comment]
Closing the issue for now, please feel free to reopen if this did not help.
