### ISSUE TITLE
Way to get projection state for partition?

### ISSUE THREAD

**Issue by mjgpy3** [EventStore/EventStore.UI#161]
Is there a way, from a specific projection's view, to get a projection's state for a particular partition?

If not, is this a desirable feature?

Currently when I want the answer I use an HTTP client or copy the projection into the query window and modify it to get rid of partition info (e.g. replace `fromCategory().forEachStream()` with just `.fromStream('stream-i-care-about')`).

**Comment by pgermishuys** [comment]
Specifically from the UI there is no way. The documentation describes how to get a projection's state for a partition over here: http://docs.geteventstore.com/projections/4.0.0/api/.

We could potentially look at providing a field whereby the user can provide us with a partition to go query the state for. Is this what you are looking for?

**Comment by mjgpy3** [comment]
@pgermishuys that sounds great. I'd love to take a shot at this.
