### ISSUE TITLE
Question about the competing consumers UI

### ISSUE THREAD

**Issue by iamkoch** [EventStore/EventStore.UI#174]
Hi there

I'm interested in what the coloured dot signifies. What do the colours mean? What, if anything, should cause concern?

The server is version 4.0.1, the client is .Net using EventStore.Client version 4.0.0.

I have a single node subscribed to a persistent subscription, with a test app appending a message every 10 seconds to the stream backing the persistent subscription. The UI shows a red dot with a 1 / 0. The dot flickers green and the count goes to 2 / 0, then the red dot returns. This repeats up to a count of 10, at which point the green dot becomes persistent and the count resets to 0 / 0.

Logging within the EventAppeared method prove that the message is being processed by the client code, though this doesn't appear to be the case in our deployed code.

Any input is appreciated.

**Comment by mjgpy3** [comment]
I and the folks at @MatrixSolutions tend to have these exact same questions.

I'd love to update the UI if someone on the @EventStore team would provide insights as to what's going on with the above questions.

**Comment by mjgpy3** [comment]
@iamkoch [this code](https://github.com/EventStore/EventStore.UI/blob/762c04fb1e9e2cd48ca61026649f2f90933a4415/src/js/modules/competing/services/SubscriptionsMapper.js#L36-L45) may help you understand what the dot means.

where `subscription-active` means "green dot" and `behind-notcatchingup` means red.

**Comment by iamkoch** [comment]
I spotted those classes on the dot. Sadly they didn't provide much insight. The messages are still being processed by the subscriber, so who is catching up?

**Comment by pgermishuys** [comment]
There's actually been a number of questions about this very same status indicator. It might be worth revisiting.

The idea is to give the user a quick glance as to the health of the persistent subscription.

**Comment by iamkoch** [comment]
I would define healthy as delivering messages successfully. I'm unsure where a red dot fits into this

**Comment by hayley-jean** [comment]
Closing this in favor of https://github.com/EventStore/EventStore.UI/issues/316
