### ISSUE TITLE
'#' in stream name returns stream not found in front end

### ISSUE THREAD

**Issue by iamkoch** [EventStore/EventStore.UI#188]
I am migrating a pet project from MongoDb to eventstore. Some of my aggregate ids contain hashtags: e.g., `#football`

The TCP API is able to return the events from the stream without issue, however, the UI cannot.

The UI displays the stream name correctly in the 'recently created streams' list, but clicking the link or navigating to it directly via the URI causes a 404.

**Comment by hayley-jean** [comment]
This has been fixed: https://github.com/EventStore/EventStore.UI/pull/224#issuecomment-1125684657
