### ISSUE TITLE
Query not work in version 4.1.1.0

### ISSUE THREAD

**Issue by dumbelovic** [EventStore/EventStore.UI#197]
I use version 4.1.1.0. I enter in query window:

fromStream('test')
.when({
     $init : function(s,e) { return {count : 0} },
     $any : function(s,e) { s.count += 1 }
     }
);

Mesage is: Query not updated.

**Comment by bidva** [comment]
same here 
![image](https://user-images.githubusercontent.com/8351624/41131335-2509855a-6a70-11e8-9b4c-b69562b16d71.png)
the reason is call has 405 (Method Not Allowed) exception

**Comment by shaan1337** [comment]
Hello @dumbelovic

Thanks for reporting this bug. We've identified and fixed it in this PR a few days ago:
https://github.com/EventStore/EventStore/pull/1644

It will be available in the next release/hotfix release.

**Comment by shaan1337** [comment]
@mattcanty unfortunately there is no work around but the fix will be out in 5.0 (expected to be released this month). We will also backport the fix to v4.

**Comment by tambeau** [comment]
This issue is closed ... resolved in release 5.0, release specified is no longer supported
