### ISSUE TITLE
Migrate away from bower to npm/yarn

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore.UI#209]
https://snyk.io/blog/bower-is-dead/
Bower is now deprecated and we should migrate to npm or yarn.

We can also consider migrating from npm to yarn: https://yarnpkg.com/en/ which provides checksums, complete offline mode and parallel installation. Migrating to yarn will allow us to use `bower-away`: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by SeanFarrow** [comment]
I wonder whether it's worth enlarging this effort to upgrade the Angular version to v7/8?
Should i open a separate issue for that?
