### ISSUE TITLE
UI Bug 2 events with same id 

### ISSUE THREAD

**Issue by Lougarou** [EventStore/EventStore.UI#217]
Projections dependent on emitted streams are not reset automatically and this caused 2 events with the same event id to be present in the same stream ( For example by_category stream ). 
​
This causes the UI to not show the events although they are present.

Ticket: 1164

**Comment by FeepingCreature** [comment]
Dupe of https://github.com/EventStore/EventStore.UI/issues/99 .

**Comment by oskardudycz** [comment]
Closing that as duplicate of #99
