### ISSUE TITLE
Is a specific version of Node required?

### ISSUE THREAD

**Issue by StuartFergusonVme** [EventStore/EventStore.UI#230]
I was looking at trying to get the UI source running locally to look at making a small change.

However I am coming across an issue when running "gulp connect" which indicates that the node version I am running v12.13.0 is not compatible with the version of gulp being used v3.9.1.

Can anyone confirm if there is a specific version of node that I should be using to get this code running.

**Comment by pgermishuys** [comment]
Hi @StuartFergusonVme. Unfortunately you need 10.x.

**Comment by StuartFergusonVme** [comment]
Thanks for the quick reply @pgermishuys.

**Comment by pgermishuys** [comment]
@StuartFergusonVme let me know if you need any further help!
