### ISSUE TITLE
Persistent Subscription - Button to view Parked Messages

### ISSUE THREAD

**Issue by StuartFergusonVme** [EventStore/EventStore.UI#231]
Add a new button to the persistent subscription row which takes the user directly to the parked queue for the Stream/Group combination.

**Comment by StuartFergusonVme** [comment]
I have been looking at making this change myself but I am unfamiliar with the code structure of the UI.

I have managed to get the Uri build for the subscription parked queue but I am unsure how to redirect the browser to the screen showing the parked queue, is there a specific helper method for doing redirection on a button click?

**Comment by StuartFergusonVme** [comment]
Here is the code I have tried adding to 'subscription.row.tpl.html'

I have tried this:
```
<li ng-show="$root.isAdminOrOps" class="page-nav__item">
            <a ng-click="$parent.viewParkedMessages(esSubscription.eventStreamId, esSubscription.groupName)">View Parked Messages</a>
        </li>
```
and this 
```
<li ng-show="$root.isAdminOrOps" class="page-nav__item">
            <a ui-sref="$parent.viewParkedMessages(esSubscription.eventStreamId, esSubscription.groupName)">View</a>
        </li>
```

**Comment by StuartFergusonVme** [comment]
I have managed to make this change and have it working locally.

Is there a set process I need to go through to get this pushed up for a pull request to get this merged into the main source code for the UI?

**Comment by pgermishuys** [comment]
Sorry @StuartFergusonVme. I have been occupied today. Didn't see this until this notification came through.
Opening a PR is good enough to get it reviewed and merged if all is well.

**Comment by StuartFergusonVme** [comment]
Hi @pgermishuys.

I seem to be unable to push my remote branch to the EventStore.UI repository, rejected with an HTTP error 403.

**Comment by pgermishuys** [comment]
You would need to fork this repository.

**Comment by StuartFergusonVme** [comment]
Ok perfect, I have done this and raised a PR for this change.
