### ISSUE TITLE
Update stream ACL via UI doesn't work when behind HTTPS proxy

### ISSUE THREAD

**Issue by maio** [EventStore/EventStore.UI#247]
**Describe the bug**

Update stream ACL via UI doesn't work when it's running behind HTTPS proxy.

Request fails due to mixed content error as it uses `http://` instead of `https://`. Other forms (e.g., add new event) work as expected.

**To Reproduce**
1. Setup EventStore so that Admin UI runs behind HTTPS proxy.
2. Go to any stream page and hit `Edit ACL` button
3. Fill form
4. Submit

**Expected behavior**

ACL is updated and I see success message.

**Actual behavior**

I get `could not update alc` alert (contains typo). And in JavaScript console I see that it tried to issue request to `http://my-host.com:443/streams/$$my-stream/incoming/ca5541fc-38c4-4b18-8acd-3202c55e3eed`.

I would expect to see request to `https://my-host.com/streams/$$my-stream/incoming/ca5541fc-38c4-4b18-8acd-3202c55e3eed`.

**EventStore details**
 - EventStore server version: 5.0.7.0

**Comment by hayley-jean** [comment]
Closing this as version 5 is no longer supported. This should not be an issue with a secure v20.10 or v21.10 node
