### ISSUE TITLE
Intermittent Unknown Error when Managing Projections

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore.UI#277]
![image](https://user-images.githubusercontent.com/5140165/99796667-2b4eb300-2b2e-11eb-8101-8de4221f5b12.png)

- Cluster
- Secure mode
- Atom Pub Enabeled

Reproduction Steps  :
- Go to Projections
- Start $by_category
- Go back to projections

**Comment by dhingrak** [comment]
I have followed the reproduction steps but I am not seeing this behavior in EventStore 22.10.0

**Comment by hayley-jean** [comment]
Thanks for testing, closing this for now then
