### ISSUE TITLE
Unfold all events with one click

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore.UI#294]
![](https://uploads.linear.app/a2a29b63-594b-4491-8437-5f7f43da2367/c8b76f2a-a415-4100-9c4d-7ca5cfb2696f/5bf9f8fc-c78d-409a-96ed-0a376850aca6)

One this screen, add a new button which lets you unfolder all the JSON events.
If I am searching through the events, I need to click "JSON" then I can search for something specific.
I appreciate I could use a query to acheive this, but sometimes a find on actual text on the browser is faster.

<sub>[UI-213](https://linear.app/eventstore/issue/UI-213/unfold-all-events-with-one-click)</sub>

**Comment by gregoryyoung** [comment]
This seems like a relatively easy to add feature and one that could be useful.

**Comment by ylorph** [comment]
Check if we have this feature for the new UI
 @George-Payne ?

**Comment by alexeyzimarev** [comment]
I will suggest it for the new UI. I don't think we'll do anything like that in the green UI.

**Comment by alexeyzimarev** [comment]
test again

**Comment by alexeyzimarev** [comment]
We are considering this feedback for the new UI as we don't plan to make significant changes in the old UI.
