### ISSUE TITLE
NaN is not a valid event number when opening deleted event from $all

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore.UI#295]
Clicking through a deleted event from $all in the UI results in an error, either showing `failed to load event content for stream '{streamName}': [object Object]` or `failed to load event content for stream '{streamName}': NaN is not valid event number`.

![DeletedEventNaN](https://user-images.githubusercontent.com/5140165/131462829-4ab808de-95e6-493f-bbbb-3eee9b35e4bd.png)

## To reproduce

The easiest way to reproduce this is to write multiple metadata events for a stream. Setting a maxCount on an existing stream will also show the error.

1. Start Event Store with `--enable-atompub-over-htttp`
2. Through the UI, create 2 events in `test-stream`
3. Create 2 `$metadata` events in `$$test-stream` that sets the `$maxCount` to 1. For example:
![image](https://user-images.githubusercontent.com/5140165/131463422-53268b3f-9c0a-43f4-926a-7ac5b1395234.png)
4. Navigate to the $all stream and click on `0@test-stream`. You'll get the `[object Object]` error.
5. Navigate back to the $all stream and click on `0@$$test-stream`. You'll get the NaN error.

**Comment by tambeau** [comment]
This may be tied to: [Steve Blair bug report](https://github.com/EventStore/EventStore.UI/issues/306)
