### ISSUE TITLE
Rename "Dead" node state to "Unreachable"

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore.UI#313]
Often the UI will show a node as "Dead" when in fact it is still running but has not been able to respond to a gossip message or has lost connection. We should show "Unreachable" in the UI instead to show that the node itself may not be down.

Note: This only covers changing the name shown in the cluster status page of the UI. The gossip that is sent from the server should not be changed.

**Comment by ylorph** [comment]
Solved in
https://github.com/EventStore/EventStore.UI/pull/329
