### ISSUE TITLE
"Add new like this" works incorrectly with metadata events

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore.UI#315]
Opening this to clarify https://github.com/EventStore/EventStore.UI/issues/204
Steps to reproduce:
1. Create some events in a stream `test-stream`
2. In the UI go to the stream, then click "metadata"
3. You see the following screen:

![image](https://user-images.githubusercontent.com/5140165/157067041-2d39b8fb-eee2-4237-907d-407129e52f08.png)

5. Click "Add New Like This"
6. You see the following screen:

![image](https://user-images.githubusercontent.com/5140165/157067330-083bbff9-e844-47ed-b050-bd143520fdaa.png)

The issues with this are:

1. The stream it is appending to should be `$test-stream`. i.e. The metadata stream and not the original stream.
2. The event type should be `$metadata`.
3. The empty data and metadata fields should be `{}`, rather than empty.

**Comment by ylorph** [comment]
WIll be handled in the new UI
