### ISSUE TITLE
Improvement: Show accumulation phase in scavenge stream

### ISSUE THREAD

**Issue by Lougarou** [EventStore/EventStore.UI#357]
Accumulation phase is not shown in the UI. Customers trying the new scavenge do not know if scavenge is actually running unless they look at the logs. This can confuse them. Suggestion for improvement would be to show that the accumulation phase has started.

![](https://uploads.linear.app/a2a29b63-594b-4491-8437-5f7f43da2367/3670ce95-6255-4081-8d9c-2c64e0d6581d/93626325-e5f2-4406-b53d-f7cdc06515f0)

<sub>[DB-119](https://linear.app/eventstore/issue/DB-119/improvement-show-accumulation-phase-in-scavenge-stream)</sub>

**Comment by alexeyzimarev** [comment]
Added [UI-214](https://linear.app/eventstore/issue/UI-214/show-scavenge-phases-in-the-ui)
