### ISSUE TITLE
Font hurts my eyes

### ISSUE THREAD

**Issue by ascjones** [EventStore/EventStore.UI#38]
Like the new UI, but the font actually hurts my eyes (at least on Chrome in Windows). Particularly the bold on the Gossip page. No doubt it looks lovely on the Mac.

![image](https://cloud.githubusercontent.com/assets/75586/5009991/1ac0c2c0-6a65-11e4-8982-de4bfc5a535d.png)

**Comment by pgermishuys** [comment]
Issue was resolved with #41
