### ISSUE TITLE
Force wrap if text is too wide

### ISSUE THREAD

**Issue by nmehlei** [EventStore/EventStore.UI#39]
I have a use case where I need to include a rather large blob of escaped json inside my metadata.
Since this is not being wrapped in the Stream Browser, the table is widened to extreme widths (17000 for example), which makes it very hard to use the UI as one has to scroll all the way to the right to close an opened event and other columns like the Type and the Timestamp are also very hard to read/find.

Here is a screenshot to show the problem: https://dl.dropboxusercontent.com/u/19676954/EventStoreUI-Wrap.png

Would be awesome if either one were able to force a text wrap inside the json output field or if this would be scrollable for itself, so one would not move the other controls and outputs so far away when expanded.

**Comment by pgermishuys** [comment]
This change has been made. Closing this issue for now.
