### ISSUE TITLE
qw

### ISSUE THREAD

**Issue by thecov** [EventStore/EventStore.UI#52]

**Comment by gregoryyoung** [comment]
I am more used to seeing wq!

On Thu, Jan 15, 2015 at 4:57 PM, thecov <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore.UI/issues/52>.
>



-- 
Studying for the Turing test

**Comment by pgermishuys** [comment]
Going to close this issue, if this was a legit issue, please provide more details.
