### ISSUE TITLE
Query doesnt work

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore.UI#53]
My guess is if you test it any fromCategory() etc one will but not a basic fromall()

Saw same thing in esquery (looks like how projections return from queries changed) if its a single result use resultUri if its multiple results use resultStreamUri which is an atom feed

see logic here https://github.com/EventStore/EventStore/tree/esquery

**Comment by briandonahue** [comment]
Seems like fromCategory() does not work either.  Here is my query:
```
fromCategory('proddebug')
  .when({
     "$init": function(){
         return {
             count: 0
         };
     },
     "$any": function(s,e){
        s.count++;
        return s;
     }
  })
```

I still see nothing in the state window, not even `{ count: 0 }`

I also don't see a textarea/box like I used to in 2.x UI.  Screenshot attached.

![screen shot 2015-01-20 at 6 16 15 pm](https://cloud.githubusercontent.com/assets/40084/5828316/c4efae04-a0d0-11e4-9479-5e54a572409b.png)

**Comment by gregoryyoung** [comment]
do you have your projections turned on $ce etc?

On Wed, Jan 21, 2015 at 1:19 AM, Brian Donahue <notifications@github.com>
wrote:

> Seems like fromCategory() does not work either. Here is my query:
>
> fromCategory('proddebug')
>   .when({
>      "$init": function(){
>          return {
>              count: 0
>          };
>      },
>      "$any": function(s,e){
>         s.count++;
>         return s;
>      }
>   })
>
> I still see nothing in the state window, not even { count: 0 }
>
> I also don't see a textarea/box like I used to in 2.x UI. Screenshot
> attached.
>
> [image: screen shot 2015-01-20 at 6 16 15 pm]
> <https://cloud.githubusercontent.com/assets/40084/5828316/c4efae04-a0d0-11e4-9479-5e54a572409b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore.UI/issues/53#issuecomment-70755023>
> .
>



-- 
Studying for the Turing test

**Comment by briandonahue** [comment]
Yes, $ce-proddebug has events in it, confirmed in stream browser.

**Comment by gregoryyoung** [comment]
what do you get from esquery?

On Wed, Jan 21, 2015 at 1:20 AM, Brian Donahue <notifications@github.com>
wrote:

> Yes, $ce-proddebug has events in it, confirmed in stream browser.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore.UI/issues/53#issuecomment-70755214>
> .
>



-- 
Studying for the Turing test

**Comment by briandonahue** [comment]
still pulling down/building the new branch.  Do you want me to test in 3.0.1?

**Comment by gregoryyoung** [comment]
sure

On Wed, Jan 21, 2015 at 1:21 AM, Brian Donahue <notifications@github.com>
wrote:

> still pulling down/building the new branch. Do you want me to test in
> 3.0.1?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore.UI/issues/53#issuecomment-70755308>
> .
>



-- 
Studying for the Turing test

**Comment by briandonahue** [comment]
```
Query started. Press esc to cancel.
Query Completed in: 00:00:06.7862057

An error has occured
Value cannot be null.
Parameter name: requestUri
```

**Comment by gregoryyoung** [comment]
let me test on the new one here

On Wed, Jan 21, 2015 at 1:22 AM, Brian Donahue <notifications@github.com>
wrote:

> Query started. Press esc to cancel.
> Query Completed in: 00:00:06.7862057
>
> An error has occured
> Value cannot be null.
> Parameter name: requestUri
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore.UI/issues/53#issuecomment-70755498>
> .
>



-- 
Studying for the Turing test

**Comment by briandonahue** [comment]
To make sure I am doing the right thing:
```c:\software\eventstore>EventStore.Query.exe
No server set defaulting to http://127.0.0.1:2113/
username:admin
password:

es:> q
fromCategory('proddebug')
  .when({
     "$init": function(){
         return {
             count: 0
         };
     },
     "$any": function(s,e){
        s.count++;
        return s;
     }
  })

Query started. Press esc to cancel.
Query Completed in: 00:00:06.7862057

An error has occured
Value cannot be null.
Parameter name: requestUri
es:>
```

**Comment by briandonahue** [comment]
I have to run to pick up my daughter, but will try the new build later tonight and/or tomorrow.  Thanks for the rapid feedback!

**Comment by gregoryyoung** [comment]
btw I meant a fromCategory.foreach() ...

On Wed, Jan 21, 2015 at 1:26 AM, Brian Donahue <notifications@github.com>
wrote:

> I have to run to pick up my daughter, but will try the new build later
> tonight and/or tomorrow. Thanks for the rapid feedback!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore.UI/issues/53#issuecomment-70755916>
> .
>



-- 
Studying for the Turing test
