### ISSUE TITLE
Fix copy and paste

### ISSUE THREAD

**Issue by ouro-ouroboros** [EventStore/EventStore.UI#60]
Selected text in the UI is unselected during screen refresh making it difficult to copy and paste data from the UI.

**Comment by nmehlei** [comment]
Duplicate of: https://github.com/EventStore/EventStore.UI/issues/40

**Comment by gregoryyoung** [comment]
I believe this is already fixed.

At least it appears to be fixed here tested on the event + stream pages

**Comment by gregoryyoung** [comment]
Ah nm I got it when expanding json on stream browser

**Comment by pgermishuys** [comment]
I will attempt to resolve this in the next couple of days.

**Comment by pgermishuys** [comment]
In the branch copy-to-clipboard branch i've added a copy to clipboard button. This will copy the data from the event into the clipboard.

![image](https://cloud.githubusercontent.com/assets/1062417/7074020/d698e520-def7-11e4-84fd-1a3120a7795b.png)

**Comment by rcknight** [comment]
This has been fixed now that pull #62 has been merged
