### ISSUE TITLE
Navigation of linked events does not show original stream

### ISSUE THREAD

**Issue by dnauck** [EventStore/EventStore.UI#70]
With EventStore 2.0.1 it was possible to browse the ```$et-``` and ```$ce-``` stream via webui and navigate to the original streams of the events. That was quiet helpful.

With the new webui of eventstore 3 its not possible anymore. I only see name and links of the actual stream and cannot navigate to the original stream. Please take a look at the following screenshots that shows the difference:

EventStore 2.0.1:
![eventstore-2 0 1](https://cloud.githubusercontent.com/assets/97584/8126577/f8403c58-10ef-11e5-989e-d2f14e1eadc2.PNG)

EventStore 3.0.5:
![eventstore-3 0 5](https://cloud.githubusercontent.com/assets/97584/8126580/01a41436-10f0-11e5-9dca-0fe591603f5d.PNG)

Event Details:

EventStore 2.0.1:
![eventstore-2 0 1-2](https://cloud.githubusercontent.com/assets/97584/8126622/8c928e74-10f0-11e5-9164-77497fac8d57.PNG)

EventStore 3.0.5:
![eventstore-3 0 5-2](https://cloud.githubusercontent.com/assets/97584/8126626/947201d8-10f0-11e5-853d-ac11bb44f740.PNG)
(Here i can only navigate back to the ```$ce-``` stream)

Is it possible to add that functionality back? Thanks!

**Comment by pgermishuys** [comment]
Will look into this and let you know.
Thanks!

**Comment by pgermishuys** [comment]
This looks fairly odd, this might be related to writing to the $ce-system stream directly?
@dnauck can you confirm this is the case and not an issue?

**Comment by gregoryyoung** [comment]
@pgermishuys it looks like its just showing local name vs resolved name on linktos

**Comment by dnauck** [comment]
Looks like @pgermishuys was right.

Due issue EventStore#503 i wrote a small replicator that writes events from 2.0.1 to 3.0.5.
I'm using this filter to filter out all system events and link-tos:

```csharp
.Where(@event => !@event.Event.EventType.StartsWith("$", StringComparison.Ordinal))
.Where(@event => !@event.Event.EventStreamId.StartsWith("$", StringComparison.Ordinal))
```

But looks like i still get events that have ```@event.OriginalStreamId == "$ce-system"```.

So this here was a wrong issue afaik.

**Comment by gregoryyoung** [comment]
ah ok

On Mon, Jun 15, 2015 at 11:35 AM, Daniel Nauck <notifications@github.com>
wrote:

> Looks like @pgermishuys <https://github.com/pgermishuys> was right.
>
> Due issue EventStore#503 i wrote a small replicator that writes events
> from 2.0.1 to 3.0.5.
> I'm using this filter to filter out all system events and link-tos:
>
> .Where(@event => !@event.Event.EventType.StartsWith("$", StringComparison.Ordinal))
> .Where(@event => !@event.Event.EventStreamId.StartsWith("$", StringComparison.Ordinal))
>
> But looks like i still get events that have @event.OriginalStreamId ==
> "$ce-system".
>
> So this here was a wrong issue afaik.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore.UI/issues/70#issuecomment-112014529>
> .
>



-- 
Studying for the Turing test
