### ISSUE TITLE
Button styling on enable user

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore.UI#71]
The button style on the "enable" button here is wrong - I suspect it's missing a class?

![enableuser](https://cloud.githubusercontent.com/assets/548524/8147054/ffda526a-1229-11e5-8230-370dc4abab30.png)

**Comment by pgermishuys** [comment]
Fixed in ff0110bb624c58480624b83239fe1ca5fa3bd9fc
![image](https://cloud.githubusercontent.com/assets/1062417/8148019/a65585f8-1287-11e5-8dbc-274ae60025bc.png)
