### ISSUE TITLE
Provide a way to set expiration of auth cookie

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore.UI#72]
This is related to a discussion on the Event Store Google Group.
https://groups.google.com/forum/#!topic/event-store/DVH4_DnYRZg

We could possibly investigate exposing configuration in the Event Store UI that would allow the user to set the expiration of the auth cookies.

**Comment by oskardudycz** [comment]
I'm closing that; I don't think that this change will going to happen, especially since we didn't have similar requests from others.
