### ISSUE TITLE
Feedback on broken projections

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore.UI#75]
One more, which I can happily move to a new Issue if you wish?

* Log into http://localhost:2114
* Run query with JS that has an error: 
```
fromCategory("SomeThing").when({
    $init : function(s,e) { return { Count : 0 } },
    $ny : function(s,e) { s.Count++; return s; }});
```
* The UI doesn't return or update the state - which is understandable - but there is NO feedback in the UI that this failed. Neither does the console show anything
* Hit "DEBUG" (as you would when something doesn't work)
* Hit "Stop"
* Hit "Run Step"

Console says;
```
[32368,16,16:36:21.131] Error while processing message EventStore.Projections.Core.Messages.EventReader
intSuggested in queued handler 'Projection Core #0'.
Specified method is not supported.
```

UI says;
![image](https://cloud.githubusercontent.com/assets/185776/9911313/6da76562-5c99-11e5-82d5-95210e4318f6.png)

Log viewer:
(nothing)

I'd expect here at least the error in the console to come back to the UI, perhaps in the Log Viewer window or something!? What am I missing?

**Comment by pgermishuys** [comment]
@ianbattersby 
We can definitely be a bit better about showing the user what is going on.
It's not very clear right now, but in a scenario where there are no events available for the projection to process (no match), the projection will just keep on running, it's up to the user to figure out

"Hey, I know I have 5 events that this projection needs to process, but it's not doing anything and just keeps running, let me look at my query again, ahhhh, a bug in the event match, it's supposed to be $any instead of $ny"

**Comment by pgermishuys** [comment]
This error shouldn't appear because of PR #80 

Thanks for the valuable feedback/comments @ianbattersb

**Comment by ianbattersby** [comment]
Many thanks, so to confirm you are saying this error is caused by there not being another event to process? Not because $ny is an error?

**Comment by pgermishuys** [comment]
You could have an event called `$ny`, this won't fail compilation and therefor not fail to create the projection.

We had a number of issues we didn't handle correctly

1. Query ran until completion, therefor no `position` came back in the header from the `/state` endpoint. This causes the the following error
```
Read Request Body Failed.
Value cannot be null.
Parameter name: token
```
We use the `position` in the query and in this case sent our payload without this property.

2. The `Run Step` shouldn't be available to press in certain scenarios, for instance, if there isn't an event waiting to be processed. This is the reason for the error above.
