### ISSUE TITLE
Updating a query-led projection in debug causes 404

### ISSUE THREAD

**Issue by ianbattersby** [EventStore/EventStore.UI#83]
I can only assume this happened because I walked away from my desk for 10 minutes? .. but I was happily updating and debugging a projection (a temporary one created via the query page by hitting DEBUG), came back 10 minutes later, changed the query and updated and got;

![image](https://cloud.githubusercontent.com/assets/185776/9930944/33af3434-5d2f-11e5-98eb-6a29a0cc4f76.png)

**Comment by pgermishuys** [comment]
This is likely due to the query having expired and being deleted. Queries are 'transient' projections and once they have run until completion they are marked for deletion.
Once again, we can be a bit better here.
