### ISSUE TITLE
Updating query with invalid DSL usage wipes query and causes console errors

### ISSUE THREAD

**Issue by ianbattersby** [EventStore/EventStore.UI#84]
**NB: using latest 3.3.0 branch in EventStore-UI**

I was working on a query in debug mode (temporary one as created via query screen) when I changed it to have an invalid EventStore usage, instead of just not working or showing an error it wiped the query from the window. The console shows it has been deleted?

* Write query
```
fromCategory("SomeCategory")
    .when({
        $init: function (s, e) {
            return {
                beenActive: false
            };
        },
        $any: function (s, e) {
            s.beenActive = true;
            return s;
        }
    });
```
* Hit debug
* Run without issue
* Do something stupid
```
fromCategory("SomeCategory")
    .foreachStream()
    .when({
        $init: function (s, e) {
            return {
                beenActive: false
            };
        },
        $any: function (s, e) {
            s.beenActive = true;
            return s;
        }
    });
```
* Hit update

Browser;
Current status: Loading definition...
Query: Empty (been wiped)

![image](https://cloud.githubusercontent.com/assets/185776/9931323/9f5e75e8-5d32-11e5-8706-3123aaab545e.png)

Console shows;
```
[15064,18,10:47:13.368] Disabling 'f2dfb5e8-dbf9-48f0-9e1d-eac22899570f' projection
[15064,18,10:47:13.490] projection stream '$projections-f2dfb5e8-dbf9-48f0-9e1d-eac22899570f-slave-1-checkpoint' deleted
[15064,18,10:47:13.490] projection stream '$projections-f2dfb5e8-dbf9-48f0-9e1d-eac22899570f-slave-0-checkpoint' deleted
[15064,18,10:47:13.490] projection stream '$projections-f2dfb5e8-dbf9-48f0-9e1d-eac22899570f-slave-2-checkpoint' deleted
```

**Comment by pgermishuys** [comment]
This will get resolved in `handle-dsl-failures` failures branch (https://github.com/EventStore/EventStore.UI/tree/handle-dsl-failures)

**Comment by ianbattersby** [comment]
Any eta for this being merged in? I'm currently running this branch and so far so good.

**Comment by jen20** [comment]
Will be in 3.3.0 I'd imagine.

**Comment by pgermishuys** [comment]
We need to bring those compilation errors back to the UI. The information is available via the /projection/{name}/statistics endpoint as `StateReason`.

We need to investigate why the server is failing to return /state on a Faulted projection. We might return an empty state here as I suspect the projection has been disposed/deleted

We can be a little more fault tolerant on our queries and possibly reshuffle them on the client to get the statistics first and if the projection status is good, then continue querying for /state etc..

**Comment by pgermishuys** [comment]
@ianbattersby I think this last commit is what I was after.
It shows why the projection is possibly faulted.

![image](https://cloud.githubusercontent.com/assets/1062417/10015132/a5ef7958-611e-11e5-8368-d0280b2aba48.png)

**Comment by ianbattersby** [comment]
That is amaze :+1:

.. as an aside we went with a slide-in-right notification in our system, we found the footer notifications just didn't work well in practice. Just another 2-penniesworth!

**Comment by pgermishuys** [comment]
Thanks for the great feedback over the last couple of days.

**Comment by ianbattersby** [comment]
@pgermishuys Should I be expecting these same feedback messages on JavaScript to also be appearing on the Query page? As currently on the 3.3.0 branch I only get them on debug - the status just says "Faulted" :(

**Comment by pgermishuys** [comment]
We should be doing that. You can expect this to be part of the 3.3.0 release. Ill get that done over the weekend
