### ISSUE TITLE
Toaster message placement

### ISSUE THREAD

**Issue by ianbattersby** [EventStore/EventStore.UI#93]
I wonder if you guys might re-consider the placement of the toaster message in the UI? Personally I find reading messages, especially errors ones with relevant content to projection queries, much easier when they appear on the right or centre.

![image](https://cloud.githubusercontent.com/assets/185776/10101078/3df57178-638e-11e5-843c-9655100e2015.png)

.. vs ..

![image](https://cloud.githubusercontent.com/assets/185776/10101332/f8295784-638f-11e5-85d2-3d6b06949e63.png)

.. but accept it's personal preference. Perhaps even just a modal dialog in the middle of the screen is actually best and forgetting toasts completely?

**Comment by jen20** [comment]
There used to be modals and they were particularly annoying. Personally I'm not opposed to moving the notifications to the top right though, @danleech any thoughts here?

**Comment by oskardudycz** [comment]
Although we all agree that Toast messages are terrible UI concepts, this won't change soon. If we come up with a new UI, we'll aim to have a better solution for error handling.
